# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/tcl/miata/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/tcl/miata/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/tcl/miata/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/tcl/miata/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/tcl/miata/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/tcl/miata/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/tcl/miata/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/tcl/miata/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/tcl/miata/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/tcl/miata/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/tcl/miata/proprietary/bin/radish:system/bin/radish \
    vendor/tcl/miata/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/tcl/miata/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/tcl/miata/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/tcl/miata/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/tcl/miata/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/tcl/miata/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/tcl/miata/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/tcl/miata/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/tcl/miata/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/tcl/miata/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/tcl/miata/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/tcl/miata/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/tcl/miata/proprietary/etc/flp.conf:system/etc/flp.conf \
    vendor/tcl/miata/proprietary/etc/izat.conf:system/etc/izat.conf \
    vendor/tcl/miata/proprietary/etc/permissions/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    vendor/tcl/miata/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/tcl/miata/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/tcl/miata/proprietary/etc/quipc.conf:system/etc/quipc.conf \
    vendor/tcl/miata/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/tcl/miata/proprietary/lib/hw/camera.vendor.msm8610.so:system/lib/hw/camera.vendor.msm8610.so \
    vendor/tcl/miata/proprietary/lib/hw/sensors.msm8610.so:system/lib/hw/sensors.msm8610.so \
    vendor/tcl/miata/proprietary/lib/libtsmoviesolid.so:system/lib/libtsmoviesolid.so \
    vendor/tcl/miata/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/tcl/miata/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/tcl/miata/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/tcl/miata/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/tcl/miata/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/tcl/miata/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/tcl/miata/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/tcl/miata/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/tcl/miata/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/tcl/miata/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/tcl/miata/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/tcl/miata/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/tcl/miata/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/tcl/miata/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/tcl/miata/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/tcl/miata/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/tcl/miata/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/tcl/miata/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/tcl/miata/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/tcl/miata/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/tcl/miata/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/tcl/miata/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/tcl/miata/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/tcl/miata/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/tcl/miata/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/tcl/miata/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/tcl/miata/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/tcl/miata/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/tcl/miata/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/tcl/miata/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/tcl/miata/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/tcl/miata/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/tcl/miata/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/tcl/miata/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/tcl/miata/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/tcl/miata/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/tcl/miata/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/tcl/miata/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/tcl/miata/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/tcl/miata/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_gc0339_sunrise_common.so:system/vendor/lib/libchromatix_gc0339_sunrise_common.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_gc0339_sunrise_default_video.so:system/vendor/lib/libchromatix_gc0339_sunrise_default_video.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_gc0339_sunrise_preview.so:system/vendor/lib/libchromatix_gc0339_sunrise_preview.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_gc0339_sunrise_snapshot.so:system/vendor/lib/libchromatix_gc0339_sunrise_snapshot.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_gc0339_sunrise.so:system/vendor/lib/libmmcamera_gc0339_sunrise.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_ov8858_common.so:system/vendor/lib/libchromatix_ov8858_common.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:system/vendor/lib/libchromatix_ov8858_default_video.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:system/vendor/lib/libchromatix_ov8858_liveshot.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_ov8858_preview.so:system/vendor/lib/libchromatix_ov8858_preview.so \
    vendor/tcl/miata/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:system/vendor/lib/libchromatix_ov8858_snapshot.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
    vendor/tcl/miata/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/tcl/miata/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/tcl/miata/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/tcl/miata/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
    vendor/tcl/miata/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/tcl/miata/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/tcl/miata/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/tcl/miata/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/tcl/miata/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/tcl/miata/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/tcl/miata/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/tcl/miata/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/tcl/miata/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/tcl/miata/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/tcl/miata/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/tcl/miata/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/tcl/miata/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/tcl/miata/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/tcl/miata/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/tcl/miata/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/tcl/miata/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/tcl/miata/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/tcl/miata/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/tcl/miata/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/tcl/miata/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/tcl/miata/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/tcl/miata/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/tcl/miata/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/tcl/miata/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/tcl/miata/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/tcl/miata/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/tcl/miata/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/tcl/miata/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/tcl/miata/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/tcl/miata/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/tcl/miata/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/tcl/miata/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/tcl/miata/proprietary/vendor/lib/rfsa/adsp/libadsp_jpege_skel.so:system/vendor/lib/rfsa/adsp/libadsp_jpege_skel.so \
    vendor/tcl/miata/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/tcl/miata/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/tcl/miata/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    qcrilmsgtunnel \
    shutdownlistener \
    TimeService \
    qcnvitems \
    qcrilhook
